#!/bin/sh

cd src/

python manage.py makemigrations subject authentication event headmaster inspector news post school
python manage.py migrate
echo "from authentication.models import ExtendedUser; ExtendedUser.objects.create_superuser('admin@admin.com','admin','admin', 3, 'password123').save()" | python manage.py shell
python manage.py runserver 0.0.0.0:8000
