# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='access_level',
            field=models.IntegerField(default=-1),
        ),
    ]
