# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='access_level',
            new_name='access_level_code',
        ),
    ]
