# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_account_access_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='scoala',
            field=models.CharField(default='', max_length=100),
        ),
    ]
