# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('authentication', '0002_auto_20161201_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='school_three',
            field=models.ForeignKey(default=-1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='thirds', to='subject.Subject'),
        ),
        migrations.AddField(
            model_name='account',
            name='subject_one',
            field=models.ForeignKey(default=-1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primers', to='subject.Subject'),
        ),
        migrations.AddField(
            model_name='account',
            name='subject_two',
            field=models.ForeignKey(default=-1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seconds', to='subject.Subject'),
        ),
        migrations.AlterField(
            model_name='account',
            name='school',
            field=models.ForeignKey(default=-1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='school.School'),
        ),
    ]
