# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_account_scoala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='scoala',
        ),
    ]
