# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('authentication', '0004_remove_account_scoala'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='school',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school', to='school.School'),
        ),
    ]
