# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(upload_to=post.models.user_directory_path)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'date',
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
    ]
