# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_status',
            field=models.IntegerField(default=-1),
        ),
    ]
