# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-10 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(upload_to=post.models.user_directory_path),
        ),
    ]
