# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extendeduser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='first_name',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='last_name',
            field=models.TextField(max_length=255),
        ),
    ]
