# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='subject.Subject'),
        ),
    ]
