# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170106_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='phone_number',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='first_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='last_name',
            field=models.TextField(max_length=50),
        ),
    ]
