# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20161202_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='access_level_code',
            field=models.IntegerField(help_text='1 stands for Inspector and 2 stands for Headmaster'),
        ),
    ]
